apiVersion: dynatrace.com/v1beta6
kind: DynaKube
metadata:
  name: kind-kind-agents
  namespace: dynatrace
spec:
  activeGate:
    capabilities:
    - routing
    - debugging
    image: public.ecr.aws/dynatrace/dynatrace-activegate:1.337.36.20260526-135434
    replicas: 3
    resources:
      limits:
        cpu: 1000m
        memory: 2Gi
      requests:
        cpu: 250m
        memory: 2Gi
  apiUrl: https://diw85600.live.dynatrace.com/api
  extensions:
    prometheus: {}
  telemetryIngest:
    protocols:
    - jaeger
    - otlp
    - statsd
    - zipkin
    serviceName: telemetry-ingest
  templates:
    extensionExecutionController:
      imageRef:
        repository: public.ecr.aws/dynatrace/dynatrace-eec
        tag: 1.337.60.20260603-063549
    otelCollector:
      imageRef:
        repository: public.ecr.aws/dynatrace/dynatrace-otel-collector
        tag: latest
  tokens: kind-kind
---
apiVersion: dynatrace.com/v1beta6
kind: DynaKube
metadata:
  name: kind-kind
  namespace: dynatrace
spec:
  activeGate:
    capabilities:
    - kubernetes-monitoring
    image: public.ecr.aws/dynatrace/dynatrace-activegate:1.337.36.20260526-135434
    replicas: 1
    resources:
      limits:
        cpu: 1000m
        memory: 6Gi
      requests:
        cpu: 200m
        memory: 6Gi
  apiUrl: https://diw85600.live.dynatrace.com/api
  logMonitoring: {}
  templates:
    kspmNodeConfigurationCollector:
      imageRef:
        repository: public.ecr.aws/dynatrace/dynatrace-k8s-node-config-collector
        tag: 1.5.4
    logMonitoring:
      imageRef:
        repository: public.ecr.aws/dynatrace/dynatrace-logmodule
        tag: 1.343.112.20260907-115430
  tokens: kind-kind
